name: Switch build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:latest
    steps:
      - uses: actions/checkout@v4

      - name: Run CMake and compile
        run: |
          source $DEVKITPRO/switchvars.sh
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS_RELEASE=-O1
          make

      - name: Upload .nro artifact
        uses: actions/upload-artifact@v4
        with:
          name: re-plants-vs-zombies.nro
          path: ./build/re-plants-vs-zombies.nro

      - name: Upload .elf artifact
        uses: actions/upload-artifact@v4
        with:
          name: re-plants-vs-zombies.elf
          path: ./build/re-plants-vs-zombies.elf
