name: Windows x86 build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32

      - name: Install dependencies
        shell: msys2 {0}
        run: pacman -S mingw-w64-i686-SDL2 mingw-w64-i686-glew mingw-w64-i686-libopenmpt mingw-w64-i686-mpg123 mingw-w64-i686-libvorbis mingw-w64-i686-libogg mingw-w64-i686-libjpeg-turbo mingw-w64-i686-libpng mingw-w64-i686-zlib

      - name: Run CMake and compile
        shell: bash
        run: |
          mkdir build
          cd build
          cmake .. -G "Unix Makefiles"
          make

      - name: Upload .exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: re-plants-vs-zombies.exe
          path: ./build/re-plants-vs-zombies.exe
